### ISSUE TITLE
templates/author.html - improperly closed H3 tag

### ISSUE THREAD

**Issue by LittleBrainz** [eliasdorneles/spidyquotes#16]
Hello,

On line 5 of templates/author.html

    <h3 class="author-title">{{ author.name }}</h2>

... note that the H3 tag is closed with H2.

As a consequence, the following Scrapy code

    response.css('h3.author-title::text').extract_first()

... will return "Albert Einstein\n    " instead of "Albert Einstein"

This can be seen at the end of the Scrapinghub tutorial at

    https://www.youtube.com/watch?v=JW_FxkSohkA

Of course, one could argue that the HTML parser used by Scrapy should fix this, as Chrome has no problem with it.

Kind regards,

Stephen Turner

**Comment by stummjr** [comment]
Hello, Stephen! That's a great catch. Thanks! :)

Would you like to send a pull request fixing this?
